export const notesActions = {
  GET_NOTES: 'GET_NOTES',
  SET_NOTES: 'SET_NOTES',
  GET_NOTE: 'GET_NOTE',
  SET_NOTE: 'SET_NOTES',
  CREATE_NOTE: 'CREATE_NOTE',
  SET_ACTIVE_NOTE: 'SET_ACTIVE_NOTE'
};

