export const NoteEditorActions = {
  NOTE_EDITOR_GET_NOTES: 'NOTE_EDITOR_GET_NOTES',
  NOTE_EDITOR_SET_NOTES: 'NOTE_EDITOR_SET_NOTES',
  NOTE_EDITOR_ERROR:'NOTE_EDITOR_ERROR',
  NOTE_EDITOR_CLEAR_ERROR:'NOTE_EDITOR_CLEAR_ERROR',
};
